### ISSUE TITLE
getOcspResponderUrl in CertificateLoader sometimes fails

### ISSUE THREAD

**Issue by rpetre** [web-eid/ocsp-php#17]
I haven't yet reproduced this in a simple script, but apparently sometimes the extension 1.3.6.1.5.5.7.48.1 is parsed as 'id-ad-ocsp' (what getOcspResponderUrl searches for, defined upstream in phpseclib) and sometimes as 'id-pkix-ocsp' (defined in AsnUtil). It's possibly due to when the certificate is actually parsed, I'll try to come up with a reproducible example.

At any point, the search in getOcspResponderUrl should probably either look up the numeric OID (if available) or at least consider the alternate name as well.

**Comment by rpetre** [comment]
I managed to reproduce the problem, apparently after AsnUtil::loadOIDs() is called (for whatever reason), the new name for the OID takes over:

```
<?php
include 'vendor/autoload.php';
use web_eid\ocsp_php\certificate\CertificateLoader;
use web_eid\ocsp_php\util\AsnUtil;

$cert_data = file_get_contents('tests/_resources/revoked.crt');

print("Before loadOIDs\n"); 
print_aia_exts((new CertificateLoader())->fromString($cert_data));

AsnUtil::loadOIDs();
print("After loadOIDs\n");
print_aia_exts((new CertificateLoader())->fromString($cert_data));


//// helper function
function print_aia_exts($loader) {
    printf("Found OCSP URL: %s\n", $loader->getOcspResponderUrl());
    $opts = $loader->getCert()->getExtension("id-pe-authorityInfoAccess");
    foreach ($opts as $opt) {
       printf("Access Method: %s, Access Location: %s\n", $opt["accessMethod"], $opt["accessLocation"]["uniformResourceIdentifier"]);
    }
}
```


output:

```
Before loadOIDs
Found OCSP URL: http://ocsp.int-x3.letsencrypt.org
Access Method: id-ad-ocsp, Access Location: http://ocsp.int-x3.letsencrypt.org
Access Method: id-ad-caIssuers, Access Location: http://cert.int-x3.letsencrypt.org/
After loadOIDs
Found OCSP URL: 
Access Method: id-pkix-ocsp, Access Location: http://ocsp.int-x3.letsencrypt.org
Access Method: id-ad-caIssuers, Access Location: http://cert.int-x3.letsencrypt.org/
```

Sorry for the quick and dirty example, I hope it showcases the issue clearly. At the very list it's a surprising behaviour that should at least be mentioned somewhere, I chased it for several days :)

**Comment by mrts** [comment]
Thanks a lot, we will schedule it for fixing. It will take some time.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the ocsp-php code was moved to web-eid-authtoken-validation-php repository.
We are happy to accept your proposals in the web-eid-authtoken-validation-php repository: https://github.com/web-eid/web-eid-authtoken-validation-php.
