### ISSUE TITLE
OCSP request is malformed

### ISSUE THREAD

**Issue by hoels** [web-eid/ocsp-php#19]
Right now, the OCSP request always contains 3 elements:
```php
$this->ocspRequest = [
    "tbsRequest" => [
        "version" => "v1",
        "requestList" => [],
        "requestExtensions" => [],
    ],
];
```

Always having `requestList` and `requestExtensions` causes additional nodes in the OCSP request, regardless of whether a value was added to it. This leads to a malformed OCSP request. For example, the Apple OCSP responder does not respond to requests created with this library anymore. The solution is to remove the empty arrays, since they will be created automatically when a value is added to it.

**Comment by kristelmerilain** [comment]
Thank you for the feedback.
I will close this issue since the ocsp-php code was moved to web-eid-authtoken-validation-php repository.
We are happy to accept your proposals in the web-eid-authtoken-validation-php repository: https://github.com/web-eid/web-eid-authtoken-validation-php.
